name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Ensure compatibility with GitHub Pages

      - name: Copy frontend folder to output
        run: |
          mkdir out
          cp -r frontend/* out/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
